
import React, { useState, useEffect } from 'react';
import { Citizen } from '../types';
import { 
  Share2, 
  MessageCircle, 
  ExternalLink, 
  Copy, 
  Check, 
  RefreshCw, 
  Zap, 
  AlertTriangle,
  FileSpreadsheet,
  Globe,
  Calendar,
  ClipboardCheck,
  Info,
  AlertCircle
} from 'lucide-react';

interface Props {
  citizens: Citizen[];
  // Omit classificationReason because it's generated by the logic hub in App.tsx
  onAdd: (citizen: Omit<Citizen, 'id' | 'status' | 'classificationReason'>) => void;
}

const SelfServiceData: React.FC<Props> = ({ citizens, onAdd }) => {
  const [googleFormUrl] = useState('https://forms.gle/gcpmNzZY2mtEi5WL9');
  const MASTER_SHEET_CSV_LINK = "https://docs.google.com/spreadsheets/d/1qQHaowvFFDXHSJCsn76TZXdb74_aXUJU1lU1EbRejmo/export?format=csv";
  
  const [csvDatabaseUrl, setCsvDatabaseUrl] = useState(MASTER_SHEET_CSV_LINK);
  const [isSyncing, setIsSyncing] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [syncYear, setSyncYear] = useState<number>(2026);
  const [toast, setToast] = useState<{ visible: boolean, message: string, title?: string, type?: 'success' | 'warning' | 'error' }>({ 
    visible: false, 
    message: '', 
    title: 'Portal Gateway',
    type: 'success' 
  });

  const availableYears = Array.from({ length: 10 }, (_, i) => 2026 + i);

  useEffect(() => {
    if (toast.visible) {
      const timer = setTimeout(() => {
        setToast({ ...toast, visible: false });
      }, 7000);
      return () => clearTimeout(timer);
    }
  }, [toast.visible]);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(googleFormUrl);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
    setToast({ visible: true, title: 'Salin Link', message: 'Tautan Google Form berhasil disalin ke clipboard.', type: 'success' });
  };

  const shareToWhatsApp = () => {
    const text = encodeURIComponent(`Halo warga Desa Wiratan, silakan isi data ekonomi Anda melalui tautan resmi ini untuk pemutakhiran data bantuan: ${googleFormUrl}`);
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const handleSyncData = async () => {
    if (!csvDatabaseUrl) {
      setToast({ visible: true, title: 'Input Kosong', message: 'Harap masukkan Link Google Sheets yang valid!', type: 'error' });
      return;
    }

    let finalUrl = csvDatabaseUrl;
    if (finalUrl.includes('/edit')) {
      finalUrl = finalUrl.replace(/\/edit.*$/, '/export?format=csv');
    }

    setIsSyncing(true);
    try {
      const fetchUrl = `${finalUrl}${finalUrl.includes('?') ? '&' : '?'}cache_bust=${Date.now()}`;
      const response = await fetch(fetchUrl);
      if (!response.ok) throw new Error('Network response was not ok');
      
      const csvText = await response.text();
      const rows = csvText.split(/\r?\n/).filter(row => row.trim() !== '');
      
      if (rows.length <= 1) {
        setToast({ visible: true, title: 'Database Kosong', message: 'Tidak ditemukan baris data pada Google Sheets tersebut.', type: 'warning' });
        setIsSyncing(false);
        return;
      }

      let addedCount = 0;
      let duplicateCount = 0;
      let incompleteCount = 0;

      for (let i = 1; i < rows.length; i++) {
        const columns = rows[i].split(/,(?=(?:(?:[^"]*"){2})*[^"]*$)/);
        
        if (columns.length >= 5) {
          const name = columns[1]?.trim().replace(/^"|"$/g, '');
          const nik = columns[2]?.trim().replace(/^"|"$/g, '').replace(/'/g, '');
          const incomeRaw = columns[3]?.trim().replace(/^"|"$/g, '').replace(/[^\d]/g, '');
          const dependentsRaw = columns[4]?.trim().replace(/^"|"$/g, '').replace(/[^\d]/g, '');
          const occupation = (columns[5] || '').trim().replace(/^"|"$/g, '');
          const genderRaw = (columns[6] || '').trim().replace(/^"|"$/g, '').toLowerCase();

          if (!name || !nik || !occupation) {
            incompleteCount++;
            continue;
          }

          const income = parseInt(incomeRaw) || 0;
          const dependents = parseInt(dependentsRaw) || 0;
          const gender: 'Laki-laki' | 'Perempuan' = (genderRaw.includes('p') || genderRaw.includes('wanita') || genderRaw.includes('perempuan')) ? 'Perempuan' : 'Laki-laki';

          const isDuplicate = citizens.some(c => (c.nik === nik || c.name.toLowerCase() === name.toLowerCase()) && c.year === syncYear);
          
          if (!isDuplicate) {
            onAdd({
              name, nik, gender, income, dependents, occupation,
              houseType: 'Permanen', floorType: 'Ubin', healthIssues: false, year: syncYear
            });
            addedCount++;
          } else {
            duplicateCount++;
          }
        } else {
          incompleteCount++;
        }
      }

      setToast({ 
        visible: true, 
        title: 'Ringkasan Portal',
        message: `Terproses: ${addedCount} baru, ${duplicateCount} duplikat, ${incompleteCount} bermasalah.`,
        type: addedCount > 0 ? 'success' : 'warning'
      });

    } catch (error) {
      setToast({ visible: true, title: 'Kesalahan Jaringan', message: 'Gagal menarik data. Periksa pengaturan "Siapa saja yang memiliki link" di Google Sheets.', type: 'error' });
    } finally {
      setIsSyncing(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Informative Toast Notification */}
      <div className={`fixed bottom-8 right-8 z-[100] transition-all duration-500 transform ${toast.visible ? 'translate-y-0 opacity-100 scale-100' : 'translate-y-12 opacity-0 scale-95 pointer-events-none'}`}>
        <div className={`bg-white/95 backdrop-blur-xl border-l-4 ${
          toast.type === 'error' ? 'border-red-600' : 
          toast.type === 'warning' ? 'border-amber-500' : 'border-indigo-600'
        } rounded-2xl shadow-[0_30px_70px_-20px_rgba(0,0,0,0.3)] p-6 flex items-center gap-5 min-w-[360px] border border-white/20`}>
          <div className={`${
            toast.type === 'error' ? 'bg-red-50 text-red-600' : 
            toast.type === 'warning' ? 'bg-amber-50 text-amber-600' : 'bg-indigo-50 text-indigo-600'
          } p-4 rounded-2xl shadow-inner`}>
            {toast.type === 'error' ? <AlertCircle size={24} /> : toast.type === 'warning' ? <Info size={24} /> : <ClipboardCheck size={24} />}
          </div>
          <div>
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] leading-none mb-1.5">{toast.title}</p>
            <p className="text-sm font-bold text-slate-800 leading-tight">{toast.message}</p>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-[2.5rem] border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-10 bg-gradient-to-br from-slate-800 to-slate-950 text-white relative">
          <div className="absolute top-0 right-0 p-12 opacity-10"><Share2 size={180} className="rotate-12" /></div>
          <div className="relative z-10">
            <div className="flex items-center gap-6 mb-8">
              <div className="p-5 bg-white/10 backdrop-blur-md rounded-[2rem] border border-white/10 shadow-xl"><Globe size={40} className="text-indigo-400" /></div>
              <div>
                <h2 className="text-3xl font-black italic uppercase tracking-tighter">Sinkronisasi Master Gateway</h2>
                <p className="text-slate-400 font-medium opacity-80 uppercase text-[10px] tracking-[0.3em]">Integrasi Google Sheets & Real-time Processing</p>
              </div>
            </div>
            <div className="flex flex-wrap gap-3">
               <button onClick={shareToWhatsApp} className="flex items-center gap-3 bg-emerald-600 text-white px-8 py-4 rounded-2xl font-black text-xs hover:scale-105 active:scale-95 transition-all shadow-xl uppercase tracking-[0.2em] italic"><MessageCircle size={18} /> Blast WA</button>
               <button onClick={() => window.open(googleFormUrl, '_blank')} className="flex items-center gap-3 bg-white/10 hover:bg-white/20 text-white px-8 py-4 rounded-2xl font-black text-xs border border-white/10 transition-all uppercase tracking-[0.2em] italic"><ExternalLink size={18} /> Cek Form</button>
            </div>
          </div>
        </div>

        <div className="p-10 space-y-10 bg-slate-50/30">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
            <div className="space-y-4">
              <div className="flex items-center gap-3 text-indigo-600">
                <div className="p-2 bg-indigo-50 rounded-lg"><Share2 size={16} /></div>
                <h4 className="text-[10px] font-black uppercase tracking-[0.2em]">1. Kanal Input Warga</h4>
              </div>
              <div className="flex gap-2">
                <input type="text" value={googleFormUrl} readOnly className="flex-1 bg-white border border-slate-200 rounded-2xl px-5 py-4 text-xs outline-none font-mono text-slate-400 truncate shadow-inner" />
                <button onClick={handleCopyLink} className="p-4 bg-white border border-slate-200 rounded-2xl hover:bg-slate-50 text-slate-600 transition-all shadow-sm active:scale-95">
                  {isCopied ? <Check size={20} className="text-emerald-500" /> : <Copy size={20} />}
                </button>
              </div>
            </div>

            <div className="space-y-4">
              <div className="flex items-center gap-3 text-emerald-600">
                <div className="p-2 bg-emerald-50 rounded-lg"><FileSpreadsheet size={16} /></div>
                <h4 className="text-[10px] font-black uppercase tracking-[0.2em]">2. Kontrol Sinkronisasi</h4>
              </div>
              <div className="flex flex-col gap-3">
                <div className="flex gap-2">
                   <div className="w-1/3 relative">
                      <select value={syncYear} onChange={(e) => setSyncYear(Number(e.target.value))} className="w-full pl-10 pr-4 py-4 rounded-2xl border border-slate-200 outline-none focus:ring-4 focus:ring-indigo-500/10 transition-all font-black text-xs bg-white appearance-none cursor-pointer">
                        {availableYears.map(year => <option key={year} value={year}>{year}</option>)}
                      </select>
                      <Calendar size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                   </div>
                   <input type="text" value={csvDatabaseUrl} onChange={(e) => setCsvDatabaseUrl(e.target.value)} className="flex-1 bg-white border border-slate-200 rounded-2xl px-5 py-4 text-xs outline-none focus:ring-4 focus:ring-indigo-500/10 transition-all font-bold shadow-inner" placeholder="Masukan link master Sheets..." />
                </div>
                <button onClick={handleSyncData} disabled={isSyncing} className={`w-full flex items-center justify-center gap-3 px-8 py-4 rounded-2xl font-black text-xs shadow-[0_15px_30px_-10px_rgba(79,70,229,0.3)] transition-all uppercase tracking-[0.2em] italic ${isSyncing ? 'bg-slate-400 cursor-not-allowed' : 'bg-indigo-600 hover:bg-indigo-700 active:scale-95'} text-white`}>
                  {isSyncing ? <RefreshCw size={18} className="animate-spin" /> : <Zap size={18} />}
                  Tarik Data Tahun {syncYear}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SelfServiceData;
